# Generated by Django 2.2 on 2020-06-06 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=20)),
                ('user_add', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_competencia_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_competencia_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('id_vaga', models.CharField(max_length=20, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Ativo'), (2, 'Inativo')])),
                ('nome_vaga', models.CharField(max_length=100)),
                ('qtd_vaga', models.SmallIntegerField()),
                ('categoria', models.CharField(choices=[(1, 'Engenharia Civil'), (2, 'Martketing'), (3, 'Tecnologia (TI)')], max_length=20)),
                ('cidade', models.SmallIntegerField(choices=[(1, 'Acre (AC)'), (2, 'Alagoas (AL)'), (3, 'Amapá (AP)'), (4, 'Amazonas (AM)'), (5, 'Bahia (BA)'), (6, 'Ceará (CE)'), (7, 'Distrito Federal (DF)'), (8, 'Espírito Santo (ES)'), (9, 'Goiás (GO)'), (10, 'Maranhão (MA)'), (11, 'Mato Grosso (MT)'), (12, 'Mato Grosso do Sul (MS)'), (13, 'Minas Gerais (MG)'), (14, 'Pará (PA)'), (15, 'Paraíba (PB)'), (16, 'Paraná (PR)'), (17, 'Pernambuco (PE)'), (18, 'Piauí (PI)'), (19, 'Rio de Janeiro (RJ)'), (20, 'Rio Grande do Norte (RN)'), (21, 'Rio Grande do Sul (RS)'), (22, 'Rondônia (RO)'), (23, 'Roraima (RR)'), (24, 'Santa Catarina (SC)'), (25, 'São Paulo (SP)'), (26, 'Sergipe (SE)'), (27, 'Tocantins (TO)')])),
                ('horario_trab', models.SmallIntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite')], null=True)),
                ('beneficios', models.SmallIntegerField(blank=True, choices=[(1, 'Previdência Privada'), (2, 'Convênio Médico'), (3, 'Vale Alimentação'), (4, 'Vale Transporte')], default=None, null=True)),
                ('descricao', models.TextField()),
                ('exp_requerida', models.TextField()),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.Competencia')),
                ('user_add', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_vagas_created_by', to=settings.AUTH_USER_MODEL)),
                ('user_upd', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='vagas_vagas_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
