# Generated by Django 2.2 on 2020-06-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaga',
            name='competencia',
        ),
        migrations.AddField(
            model_name='vaga',
            name='competencia',
            field=models.ManyToManyField(to='vagas.Competencia'),
        ),
    ]
