# Generated by Django 2.2 on 2020-06-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='date_add',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='date_upd',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='user_add',
        ),
        migrations.RemoveField(
            model_name='competencia',
            name='user_upd',
        ),
    ]
