# Generated by Django 2.2 on 2020-06-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_auto_20200607_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='horario_trab',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Manhã'), (2, 'Tarde'), (3, 'Noite'), (4, '1.º Turno'), (5, '2.º Turno'), (6, '3.º Turno')], null=True, verbose_name='Período'),
        ),
    ]
