# Generated by Django 2.2 on 2020-06-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_auto_20200607_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vagas.Competencia', verbose_name='Competências exigidas'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='nome_vaga',
            field=models.CharField(max_length=100, verbose_name='Denominação da Vaga'),
        ),
        migrations.AlterField(
            model_name='vagas',
            name='qtd_vaga',
            field=models.SmallIntegerField(verbose_name='Quantidade de vagas'),
        ),
    ]
