# Generated by Django 2.2 on 2020-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0006_auto_20200607_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='exp_requerida',
            field=models.TextField(blank=True, null=True, verbose_name='Experiências necessárias'),
        ),
    ]
