# Generated by Django 2.2 on 2020-06-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0007_auto_20200607_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='categoria',
            field=models.SmallIntegerField(choices=[(1, 'Engenharia Civil'), (2, 'Martketing'), (3, 'Tecnologia (TI)')]),
        ),
    ]
