# Generated by Django 2.2 on 2020-06-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_auto_20200607_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
