# Generated by Django 2.2 on 2020-06-07 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_auto_20200607_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='nome',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vagas',
            name='competencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vagas.Competencia', verbose_name='Competências exigidas'),
        ),
    ]
