

ESCOLARIDADE = [
    (1, "Analfabeto(a)"),
    (2, "Ensino Fundamental Completo"),
    (3, "Ensino Fundamental Incompleto"),
    (4, "Ensino Médio Incompleto"),
    (5, "Ensino Médio Completo"),
    (6, "Ensino Superior Completo"),
    (7, "Ensino Superior Incompleto"),
]

PAISES = [
    (1, "Brasil"),
    (2, "Afeganistão"),
    (3, "África do Sul"),
    (4, "Akrotiri"),
    (5, "Albânia"),
    (6, "Alemanha"),
    (7, "Andorra"),
    (8, "Angola"),
    (9, "Anguila"),
    (10, "Antárctida"),
    (11, "Antígua e Barbuda"),
    (12, "Antilhas Neerlandesas"),
    (13, "Arábia Saudita"),
    (14, "Arctic Ocean"),
    (15, "Argélia"),
    (16, "Argentina"),
    (17, "Arménia"),
    (18, "Aruba"),
    (19, "Ashmore and Cartier Islands"),
    (20, "Atlantic Ocean"),
    (21, "Austrália"),
    (22, "Áustria"),
    (23, "Azerbaijão"),
    (24, "Baamas"),
    (25, "Bangladeche"),
    (26, "Barbados"),
    (27, "Barém"),
    (28, "Bélgica"),
    (29, "Belize"),
    (30, "Benim"),
    (31, "Bermudas"),
    (32, "Bielorrússia"),
    (33, "Birmânia"),
    (34, "Bolívia"),
    (35, "Bósnia e Herzegovina"),
    (36, "Botsuana"),
    (37, "Brunei"),
    (38, "Bulgária"),
    (39, "Burquina Faso"),
    (40, "Burúndi"),
    (41, "Butão"),
    (42, "Cabo Verde"),
    (43, "Camarões"),
    (44, "Camboja"),
    (45, "Canadá"),
    (46, "Catar"),
    (47, "Cazaquistão"),
    (48, "Chade"),
    (49, "Chile"),
    (50, "China"),
    (51, "Chipre"),
    (52, "Clipperton Island"),
    (53, "Colômbia"),
    (54, "Comores"),
    (55, "Congo-Brazzaville"),
    (56, "Congo-Kinshasa"),
    (57, "Coral Sea Islands"),
    (58, "Coreia do Norte"),
    (59, "Coreia do Sul"),
    (60, "Costa do Marfim"),
    (61, "Costa Rica"),
    (62, "Croácia"),
    (63, "Cuba"),
    (64, "Dhekelia"),
    (65, "Dinamarca"),
    (66, "Domínica"),
    (67, "Egipto"),
    (68, "Emiratos Árabes Unidos"),
    (69, "Equador"),
    (70, "Eritreia"),
    (71, "Eslováquia"),
    (72, "Eslovénia"),
    (73, "Espanha"),
    (74, "Estados Unidos"),
    (75, "Estónia"),
    (76, "Etiópia"),
    (77, "Faroé"),
    (78, "Fiji"),
    (79, "Filipinas"),
    (80, "Finlândia"),
    (81, "França"),
    (82, "Gabão"),
    (83, "Gâmbia"),
    (84, "Gana"),
    (85, "Gaza Strip"),
    (86, "Geórgia"),
    (87, "Geórgia do Sul e Sandwich do Sul"),
    (88, "Gibraltar"),
    (89, "Granada"),
    (90, "Grécia"),
    (91, "Gronelândia"),
    (92, "Guame"),
    (93, "Guatemala"),
    (94, "Guernsey"),
    (95, "Guiana"),
    (96, "Guiné"),
    (97, "Guiné Equatorial"),
    (98, "Guiné-Bissa"),
    (99, "Haiti"),
    (100, "Honduras"),
    (101, "Hong Kong"),
    (102, "Hungria"),
    (103, "Iémen"),
    (104, "Ilha Bouvet"),
    (105, "Ilha do Natal"),
    (106, "Ilha Norfolk"),
    (107, "Ilhas Caimão"),
    (108, "Ilhas Cook"),
    (109, "Ilhas dos Cocos"),
    (110, "Ilhas Falkland"),
    (111, "Ilhas Heard e McDonald"),
    (112, "Ilhas Marshall"),
    (113, "Ilhas Salomão"),
    (114, "Ilhas Turcas e Caicos"),
    (115, "Ilhas Virgens Americanas"),
    (116, "Ilhas Virgens Britânicas"),
    (117, "Índia"),
    (118, "Indian Ocean"),
    (119, "Indonésia"),
    (120, "Irão"),
    (121, "Iraque"),
    (122, "Irlanda"),
    (123, "Islândia"),
    (124, "Israel"),
    (125, "Itália"),
    (126, "Jamaica"),
    (127, "Jan Mayen"),
    (128, "Japão"),
    (129, "Jersey"),
    (130, "Jibuti"),
    (131, "Jordânia"),
    (132, "Kuwait"),
    (133, "Laos"),
    (134, "Lesoto"),
    (135, "Letónia"),
    (136, "Líbano"),
    (137, "Libéria"),
    (138, "Líbia"),
    (139, "Listenstaine"),
    (140, "Lituânia"),
    (141, "Luxemburgo"),
    (142, "Maca"),
    (143, "Macedónia"),
    (144, "Madagáscar"),
    (145, "Malásia"),
    (146, "Malávi"),
    (147, "Maldivas"),
    (148, "Mali"),
    (149, "Malta"),
    (150, "Man, Isle of"),
    (151, "Marianas do Norte"),
    (152, "Marrocos"),
    (153, "Maurícia"),
    (154, "Mauritânia"),
    (155, "Mayotte"),
    (156, "México"),
    (157, "Micronésia"),
    (158, "Moçambique"),
    (159, "Moldávia"),
    (160, "Mónaco"),
    (161, "Mongólia"),
    (162, "Monserrate"),
    (163, "Montenegro"),
    (164, "Mundo"),
    (165, "Namíbia"),
    (166, "Naur"),
    (167, "Navassa Island"),
    (168, "Nepal"),
    (169, "Nicarágua"),
    (170, "Níger"),
    (171, "Nigéria"),
    (172, "Niue"),
    (173, "Noruega"),
    (174, "Nova Caledónia"),
    (175, "Nova Zelândia"),
    (176, "Omã"),
    (177, "Pacific Ocean"),
    (178, "Países Baixos"),
    (179, "Pala"),
    (180, "Panamá"),
    (181, "Papua-Nova Guiné"),
    (182, "Paquistão"),
    (183, "Paracel Islands"),
    (184, "Paraguai"),
    (185, "Per"),
    (186, "Pitcairn"),
    (187, "Polinésia Francesa"),
    (188, "Polónia"),
    (189, "Porto Rico"),
    (190, "Portugal"),
    (191, "Quénia"),
    (192, "Quirguizistão"),
    (193, "Quiribáti"),
    (194, "Reino Unido"),
    (195, "República Centro-Africana"),
    (196, "República Checa"),
    (197, "República Dominicana"),
    (198, "Roménia"),
    (199, "Ruanda"),
    (200, "Rússia"),
    (201, "Salvador"),
    (202, "Samoa"),
    (203, "Samoa Americana"),
    (204, "Santa Helena"),
    (205, "Santa Lúcia"),
    (206, "São Cristóvão e Neves"),
    (207, "São Marinho"),
    (208, "São Pedro e Miquelon"),
    (209, "São Tomé e Príncipe"),
    (210, "São Vicente e Granadinas"),
    (211, "Sara Ocidental"),
    (212, "Seicheles"),
    (213, "Senegal"),
    (214, "Serra Leoa"),
    (215, "Sérvia"),
    (216, "Singapura"),
    (217, "Síria"),
    (218, "Somália"),
    (219, "Southern Ocean"),
    (220, "Spratly Islands"),
    (221, "Sri Lanca"),
    (222, "Suazilândia"),
    (223, "Sudão"),
    (224, "Suécia"),
    (225, "Suíça"),
    (226, "Suriname"),
    (227, "Svalbard e Jan Mayen"),
    (228, "Tailândia"),
    (229, "Taiwan"),
    (230, "Tajiquistão"),
    (231, "Tanzânia"),
    (232, "Território Britânico do Oceano Índico"),
    (233, "Territórios Austrais Franceses"),
    (234, "Timor Leste"),
    (235, "Togo"),
    (236, "Tokela"),
    (237, "Tonga"),
    (238, "Trindade e Tobago"),
    (239, "Tunísia"),
    (240, "Turquemenistão"),
    (241, "Turquia"),
    (242, "Tuval"),
    (243, "Ucrânia"),
    (244, "Uganda"),
    (245, "União Europeia"),
    (246, "Uruguai"),
    (247, "Usbequistão"),
    (248, "Vanuat"),
    (249, "Vaticano"),
    (250, "Venezuela"),
    (251, "Vietname"),
    (252, "Wake Island"),
    (253, "Wallis e Futuna"),
    (254, "West Bank"),
    (255, "Zâmbia"),
    (256, "Zimbabué"),
]

PROFISSOES = [
    (1, 'Administrador(a)'),
    (2, 'Advogado(a)'),
    (3, 'Aeronauta'),
    (4, 'Agricultor(a)'),
    (5, 'Apicultor(a)'),
    (6, 'Aqüicultor(a)'),
    (7, 'Arquivista / Técnico de Arquivo'),
    (8, 'Artesão'),
    (9, 'Artista/Técnico(a) em espetáculos de diversões'),
    (10, 'Assistente Social'),
    (11, 'Atleta Profissional de Futebol'),
    (12, 'Atuário(a)'),
    (13, 'Bibliotecário'),
    (14, 'Biomédico(a)'),
    (15, 'Biólogo(a)'),
    (16, 'Bombeiro Civil'),
    (17, 'Carpinteiro(a)'),
    (18, 'Carvoejador(a)'),
    (19, 'Comerciário(a)'),
    (20, 'Contabilista'),
    (21, 'Corretor(a) de Imóveis'),
    (22, 'Corretor(a) de Seguros'),
    (23, 'Despachante Aduaneiro(a)'),
    (24, 'Economista Doméstico(a)'),
    (25, 'Economista'),
    (26, 'Educação Física'),
    (27, 'Empregado(a) Doméstico(a)'),
    (28, 'Empresário(a)'),
    (29, 'Enfermagem'),
    (30, 'Engenharia de Segurança'),
    (31, 'Engenheiro(a)/ Arquiteto(a)/ Agrônomo(a)'),
    (32, 'Enólogo(a)'),
    (33, 'Estatístico(a)'),
    (34, 'Extrativista'),
    (35, 'Farmacêutico(a)'),
    (36, 'Fisioterapeuta e Terapeuta Ocupacional'),
    (37, 'Fonoaudiólogo(a)'),
    (38, 'Garimpeiro(a)'),
    (39, 'Geógrafo(a)'),
    (40, 'Geólogo(a)'),
    (41, 'Guardador(a) e Lavador(a) de Veículos'),
    (42, 'Instrutor(a) de Trânsito(a)'),
    (43, 'Jornalista'),
    (44, 'Leiloeiro(a) Rural'),
    (45, 'Leiloeiro(a)'),
    (46, 'Marcineiro(a)'),
    (47, 'Massagista'),
    (48, 'Medicina Veterinária'),
    (49, 'Mototaxista e Motoboy'),
    (50, 'Museólogo(a)'),
    (51, 'Mãe Social'),
    (52, 'Médico(a)'),
    (53, 'Músico(a)'),
    (54, 'Nutricionista'),
    (55, 'Oceanógrafo(a)'),
    (56, 'Odontologia'),
    (57, 'Orientador(a) Educacional'),
    (58, 'Pecuarista'),
    (59, 'Pescador(a) Profissional'),
    (60, 'Peção de Rodeio(a)'),
    (61, 'Piscicultor(a)'),
    (62, 'Psicologia'),
    (63, 'Publicitário/Agenciador de Propaganda'),
    (64, 'Químico(a)'),
    (65, 'Radialista'),
    (66, 'Relações Públicas'),
    (67, 'Repentista'),
    (68, 'Representantes Comerciais Autônomos'),
    (69, 'Secretário(a) - Secretário(a) Executivo e Técnico(a) em Secretariado'),
    (70, 'Seringueiro(a)'),
    (71, 'Sociólogo(a)'),
    (72, 'Sommelier'),
    (73, 'Taxista'),
    (74, 'Tradutor(a) e Intérprete da Língua Brasileira de Sinais - LIBRAS'),
    (75, 'Turismólogo(a)'),
    (76, 'Técnico(a) em Administração'),
    (77, 'Técnico(a) em Prótese Dentária'),
    (78, 'Técnico(a) em Radiologia'),
    (79, 'Técnico(a) Industrial'),
    (80, 'Zootecnista'),
    (81, 'Outros'),
]
